// Code generated by the Encore v1.57.13 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-comics-galore-backend-v5k2.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the comics-galore-backend-v5k2 Encore application.
 */
export default class Client {
    public readonly auth: auth.ServiceClient
    public readonly billing: billing.ServiceClient
    public readonly comics: comics.ServiceClient
    public readonly reading: reading.ServiceClient
    public readonly tiers: tiers.ServiceClient
    public readonly upload: upload.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.auth = new auth.ServiceClient(base)
        this.billing = new billing.ServiceClient(base)
        this.comics = new comics.ServiceClient(base)
        this.reading = new reading.ServiceClient(base)
        this.tiers = new tiers.ServiceClient(base)
        this.upload = new upload.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    /**
     * Allows you to set the authentication data to be used for each
     * request either by passing in a static object or by passing in
     * a function which returns a new object for each request.
     */
    auth?: auth.AuthParams | AuthDataGenerator
}

export namespace auth {
    export interface AdminListUsersParams {
        Page: number
        Limit: number
        Search: string
        Sort: string
        SortDir: string
        FilterRole: string
        FilterTier: string
        FilterEmail: string
    }

    export interface AdminUser {
        id: string
        email: string
        role: string
        tier: string
        "created_at": string
        "banned_at": string
        "suspended_at": string
    }

    export interface AdminUserListResponse {
        users: AdminUser[]
        total: number
    }

    export interface AppSettings {
        "default_language": string
        "default_content_language": string
        "items_per_page": number
        "popular_tags_limit": number
        "site_name": string
        "maintenance_mode": boolean
        "registrations_open": boolean
        "max_upload_size_mb": number
        "image_serving_mode": string
        "require_email_verify": boolean
        "rate_limit": number
        "s3_presigned_ttl_min": number
        "cf_presigned_ttl_min": number
        "quota_free_gb": number
        "quota_bronze_gb": number
        "quota_silver_gb": number
        "quota_gold_gb": number
        "quota_platinum_gb": number
        "boost_1_gb": number
        "boost_1_price": number
        "boost_2_gb": number
        "boost_2_price": number
        "boost_3_gb": number
        "boost_3_price": number
        "contact_email": string
        "hide_mature_default": boolean
        "enable_comments": boolean
        "default_meta_description": string
    }

    export interface AuthParams {
        Authorization: string
    }

    export interface AuthResponse {
        token: string
        user: User
    }

    export interface BanUserParams {
        reason: string
    }

    export interface DashboardStats {
        "total_users": number
        "new_users_this_month": number
    }

    export interface LoginParams {
        email: string
        password: string
    }

    export interface NotificationPrefs {
        "email_new_from_following": boolean
        "email_support_replies": boolean
        "email_marketing": boolean
        "in_app_enabled": boolean
    }

    export interface PasswordResetConfirm {
        token: string
        password: string
    }

    export interface PasswordResetRequest {
        email: string
    }

    export interface RegisterParams {
        email: string
        password: string
    }

    export interface SeedParams {
        token: string
    }

    export interface SeedUsersResponse {
        created: number
        skipped: number
        message: string
    }

    export interface UpdateAvatarParams {
        "avatar_data": string
    }

    export interface UpdateAvatarResponse {
        "avatar_key": string
    }

    export interface UpdateUserRoleParams {
        role: string
    }

    export interface User {
        id: string
        email: string
        role: string
        tier: string
        "avatar_key": string
        "created_at": string
    }

    export interface UserPreferences {
        language: string
        "content_language": string
        "items_per_page": number
        "popular_tags_limit": number
        "email_from_following": boolean
        "email_support_replies": boolean
        "email_marketing": boolean
        "in_app_enabled": boolean
        "hide_mature": boolean
    }

    export interface UserProfile {
        id: string
        email: string
        role: string
        tier: string
        "avatar_key": string
        "created_at": string
    }

    export interface VerifyEmailParams {
        token: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.AdminBanUser = this.AdminBanUser.bind(this)
            this.AdminDashboardStats = this.AdminDashboardStats.bind(this)
            this.AdminListUsers = this.AdminListUsers.bind(this)
            this.AdminSuspendUser = this.AdminSuspendUser.bind(this)
            this.AdminUnbanUser = this.AdminUnbanUser.bind(this)
            this.AdminUnsuspendUser = this.AdminUnsuspendUser.bind(this)
            this.AdminUpdateUserRole = this.AdminUpdateUserRole.bind(this)
            this.ConfirmPasswordReset = this.ConfirmPasswordReset.bind(this)
            this.DevSeedUsers = this.DevSeedUsers.bind(this)
            this.GetAdminSettings = this.GetAdminSettings.bind(this)
            this.GetAvatar = this.GetAvatar.bind(this)
            this.GetNotificationPrefs = this.GetNotificationPrefs.bind(this)
            this.GetPreferences = this.GetPreferences.bind(this)
            this.GetProfile = this.GetProfile.bind(this)
            this.Login = this.Login.bind(this)
            this.Me = this.Me.bind(this)
            this.Register = this.Register.bind(this)
            this.RenewToken = this.RenewToken.bind(this)
            this.RequestPasswordReset = this.RequestPasswordReset.bind(this)
            this.ResendVerification = this.ResendVerification.bind(this)
            this.SaveAdminSettings = this.SaveAdminSettings.bind(this)
            this.SavePreferences = this.SavePreferences.bind(this)
            this.UpdateAvatar = this.UpdateAvatar.bind(this)
            this.UpdateNotificationPrefs = this.UpdateNotificationPrefs.bind(this)
            this.VerifyEmail = this.VerifyEmail.bind(this)
        }

        public async AdminBanUser(id: string, params: BanUserParams): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/admin/users/${encodeURIComponent(id)}/ban`, JSON.stringify(params))
        }

        public async AdminDashboardStats(): Promise<DashboardStats> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/stats`)
            return await resp.json() as DashboardStats
        }

        public async AdminListUsers(params: AdminListUsersParams): Promise<AdminUserListResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "filter_email": params.FilterEmail,
                "filter_role":  params.FilterRole,
                "filter_tier":  params.FilterTier,
                limit:          String(params.Limit),
                page:           String(params.Page),
                search:         params.Search,
                sort:           params.Sort,
                "sort_dir":     params.SortDir,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/users`, undefined, {query})
            return await resp.json() as AdminUserListResponse
        }

        public async AdminSuspendUser(id: string, params: BanUserParams): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/admin/users/${encodeURIComponent(id)}/suspend`, JSON.stringify(params))
        }

        public async AdminUnbanUser(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/admin/users/${encodeURIComponent(id)}/unban`)
        }

        public async AdminUnsuspendUser(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/admin/users/${encodeURIComponent(id)}/unsuspend`)
        }

        public async AdminUpdateUserRole(id: string, params: UpdateUserRoleParams): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/admin/users/${encodeURIComponent(id)}/role`, JSON.stringify(params))
        }

        public async ConfirmPasswordReset(params: PasswordResetConfirm): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/auth/password-reset/confirm`, JSON.stringify(params))
        }

        public async DevSeedUsers(params: SeedParams): Promise<SeedUsersResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/dev/seed-users`, JSON.stringify(params))
            return await resp.json() as SeedUsersResponse
        }

        public async GetAdminSettings(): Promise<AppSettings> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/settings`)
            return await resp.json() as AppSettings
        }

        public async GetAvatar(): Promise<UpdateAvatarResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/me/avatar`)
            return await resp.json() as UpdateAvatarResponse
        }

        public async GetNotificationPrefs(): Promise<NotificationPrefs> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/me/notification-preferences`)
            return await resp.json() as NotificationPrefs
        }

        public async GetPreferences(): Promise<UserPreferences> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/me/preferences`)
            return await resp.json() as UserPreferences
        }

        public async GetProfile(): Promise<UserProfile> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/me/profile`)
            return await resp.json() as UserProfile
        }

        public async Login(params: LoginParams): Promise<AuthResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth/login`, JSON.stringify(params))
            return await resp.json() as AuthResponse
        }

        public async Me(): Promise<User> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/auth/me`)
            return await resp.json() as User
        }

        public async Register(params: RegisterParams): Promise<AuthResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/auth/register`, JSON.stringify(params))
            return await resp.json() as AuthResponse
        }

        public async RenewToken(): Promise<AuthResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/auth/renew`)
            return await resp.json() as AuthResponse
        }

        public async RequestPasswordReset(params: PasswordResetRequest): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/auth/password-reset/request`, JSON.stringify(params))
        }

        public async ResendVerification(): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/auth/resend-verification`)
        }

        public async SaveAdminSettings(params: AppSettings): Promise<AppSettings> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/admin/settings`, JSON.stringify(params))
            return await resp.json() as AppSettings
        }

        public async SavePreferences(params: UserPreferences): Promise<UserPreferences> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/me/preferences`, JSON.stringify(params))
            return await resp.json() as UserPreferences
        }

        public async UpdateAvatar(params: UpdateAvatarParams): Promise<UpdateAvatarResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/me/avatar`, JSON.stringify(params))
            return await resp.json() as UpdateAvatarResponse
        }

        public async UpdateNotificationPrefs(params: NotificationPrefs): Promise<NotificationPrefs> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("PATCH", `/me/notification-preferences`, JSON.stringify(params))
            return await resp.json() as NotificationPrefs
        }

        public async VerifyEmail(params: VerifyEmailParams): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/auth/verify-email`, JSON.stringify(params))
        }
    }
}

/**
 * Package billing implements the PaymentsProvider interface using the
 * NowPayments REST API.
 * 
 * Full API reference: backend/billing/nowpayments-openapi.yaml
 * Base URL: https://api.nowpayments.io
 */
export namespace billing {
    export interface AdminDeposit {
        id: string
        "user_id": string
        "provider_deposit_id": string
        "amount_crypto": string
        "currency_crypto": string
        "amount_usd_cents": number
        status: string
        "pay_address": string
        "created_at": string
        "completed_at": string
    }

    export interface AdminDepositList {
        deposits: AdminDeposit[]
        total: number
    }

    export interface AdminListDepositsParams {
        Page: number
        Limit: number
        Search: string
        Sort: string
        SortDir: string
        FilterStatus: string
    }

    export interface AdminListPaymentsParams {
        Page: number
        Limit: number
        Search: string
        Sort: string
        SortDir: string
        FilterStatus: string
        FilterTier: string
    }

    export interface AdminListSubscriptionsParams {
        Page: number
        Limit: number
        Search: string
        Sort: string
        SortDir: string
        FilterStatus: string
        FilterTier: string
        FilterUserID: string
    }

    export interface AdminPayment {
        id: string
        "provider_payment_id": string
        "user_id": string
        "subscription_id": string
        tier: string
        interval: string
        "amount_crypto": string
        "currency_crypto": string
        "amount_usd_cents": number
        status: string
        "created_at": string
    }

    export interface AdminPaymentList {
        payments: AdminPayment[]
        total: number
    }

    export interface AdminSubList {
        subscriptions: AdminSubscription[]
        total: number
    }

    export interface AdminSubscription {
        id: string
        "user_id": string
        "plan_id": string
        status: string
        active: boolean
        tier: string
        "activated_at": string
        "expires_at": string
        "created_at": string
    }

    export interface BalanceEntry {
        Amount: number
        PendingAmount: number
    }

    export interface BillingStats {
        "total_revenue": number
        "active_revenue": number
        "recent_revenue": number
        "total_deposits": number
        "total_payments": number
        "active_subscriptions": number
        "revenue_by_tier": RevenueByTier[]
    }

    export interface CheckBalanceResponse {
        balances: { [key: string]: BalanceEntry }
    }

    export interface CreateDepositParams {
        "plan_id": string
        crypto: string
        Host: string
    }

    export interface CreateDepositResponse {
        "deposit_id": string
        "pay_address": string
        "pay_amount": number
        "pay_currency": string
        "plan_id": string
    }

    export interface CreateSubParams {
        "plan_id": string
    }

    export interface CreateSubResponse {
        "subscription_id": string
        status: string
    }

    export interface EstimatePriceParams {
        "plan_id": string
        crypto: string
    }

    export interface EstimateResponse {
        EstimatedAmount: number
        FromCurrency: string
        ToCurrency: string
    }

    export interface PollDepositResponse {
        completed: boolean
    }

    export interface PollSubResponse {
        active: boolean
    }

    export interface RevenueByTier {
        tier: string
        revenue: number
    }

    export interface SeedBillingParams {
        token: string
    }

    export interface SeedBillingResponse {
        created: number
        skipped: number
        message: string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.AdminListDeposits = this.AdminListDeposits.bind(this)
            this.AdminListPayments = this.AdminListPayments.bind(this)
            this.AdminListSubscriptions = this.AdminListSubscriptions.bind(this)
            this.CheckBalance = this.CheckBalance.bind(this)
            this.CreateDeposit = this.CreateDeposit.bind(this)
            this.CreateSubscription = this.CreateSubscription.bind(this)
            this.DepositWebhook = this.DepositWebhook.bind(this)
            this.DevSeedBilling = this.DevSeedBilling.bind(this)
            this.EstimatePrice = this.EstimatePrice.bind(this)
            this.GetBillingStats = this.GetBillingStats.bind(this)
            this.PollDeposit = this.PollDeposit.bind(this)
            this.PollSubscription = this.PollSubscription.bind(this)
            this.SubscriptionWebhook = this.SubscriptionWebhook.bind(this)
        }

        public async AdminListDeposits(params: AdminListDepositsParams): Promise<AdminDepositList> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "filter_status": params.FilterStatus,
                limit:           String(params.Limit),
                page:            String(params.Page),
                search:          params.Search,
                sort:            params.Sort,
                "sort_dir":      params.SortDir,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/deposits`, undefined, {query})
            return await resp.json() as AdminDepositList
        }

        public async AdminListPayments(params: AdminListPaymentsParams): Promise<AdminPaymentList> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "filter_status": params.FilterStatus,
                "filter_tier":   params.FilterTier,
                limit:           String(params.Limit),
                page:            String(params.Page),
                search:          params.Search,
                sort:            params.Sort,
                "sort_dir":      params.SortDir,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/payments`, undefined, {query})
            return await resp.json() as AdminPaymentList
        }

        public async AdminListSubscriptions(params: AdminListSubscriptionsParams): Promise<AdminSubList> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "filter_status":  params.FilterStatus,
                "filter_tier":    params.FilterTier,
                "filter_user_id": params.FilterUserID,
                limit:            String(params.Limit),
                page:             String(params.Page),
                search:           params.Search,
                sort:             params.Sort,
                "sort_dir":       params.SortDir,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/subscriptions`, undefined, {query})
            return await resp.json() as AdminSubList
        }

        public async CheckBalance(): Promise<CheckBalanceResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/billing/check-balance`)
            return await resp.json() as CheckBalanceResponse
        }

        public async CreateDeposit(params: CreateDepositParams): Promise<CreateDepositResponse> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                host: params.Host,
            })

            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                crypto:    params.crypto,
                "plan_id": params["plan_id"],
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/billing/create-deposit`, JSON.stringify(body), {headers})
            return await resp.json() as CreateDepositResponse
        }

        public async CreateSubscription(params: CreateSubParams): Promise<CreateSubResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/billing/create-subscription`, JSON.stringify(params))
            return await resp.json() as CreateSubResponse
        }

        public async DepositWebhook(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/webhooks/nowpayments/deposit`, body, options)
        }

        public async DevSeedBilling(params: SeedBillingParams): Promise<SeedBillingResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/dev/seed-billing`, JSON.stringify(params))
            return await resp.json() as SeedBillingResponse
        }

        public async EstimatePrice(params: EstimatePriceParams): Promise<EstimateResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/billing/estimate-price`, JSON.stringify(params))
            return await resp.json() as EstimateResponse
        }

        public async GetBillingStats(): Promise<BillingStats> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/billing-stats`)
            return await resp.json() as BillingStats
        }

        public async PollDeposit(id: string): Promise<PollDepositResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/billing/deposit/${encodeURIComponent(id)}/poll`)
            return await resp.json() as PollDepositResponse
        }

        public async PollSubscription(id: string): Promise<PollSubResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/billing/subscription/${encodeURIComponent(id)}/poll`)
            return await resp.json() as PollSubResponse
        }

        public async SubscriptionWebhook(method: "POST", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/webhooks/nowpayments/subscription`, body, options)
        }
    }
}

export namespace comics {
    export interface AdminListComicsParams {
        Page: number
        Limit: number
        Search: string
        Sort: string
        SortDir: string
        FilterStatus: string
        FilterAuthor: string
        FilterTitle: string
    }

    export interface AuditLogEntry {
        id: string
        "actor_id": string
        action: string
        "target_type": string
        "target_id": string
        details: string
        "created_at": string
    }

    export interface AuditLogsResponse {
        entries: AuditLogEntry[]
    }

    export interface BatchComicsParams {
        ids: string[]
    }

    export interface BulkActionParams {
        ids: string[]
        action: string
    }

    /**
     * Comic is the public representation
     */
    export interface Comic {
        id: string
        "uploader_id": string
        title: string
        author: string
        slug: string
        description: string
        "content_language": string
        status: string
        "cover_key": string
        "file_key": string
        "page_keys": string[]
        "file_size_bytes": number
        "min_tier_id": string
        "age_rating": string
        "is_premium": boolean
        tags: string[]
        "rejection_reason": string
        "published_at": string
        "view_count": number
        "download_count": number
        "like_count": number
        "fav_count": number
        "dislike_count": number
        "is_liked": boolean
        "is_favorited": boolean
        "is_disliked": boolean
        "created_at": string
        "updated_at": string
        /**
         * Resolved URLs (populated server-side, not from DB)
         */
        "cover_url": string

        "page_urls": string[]
    }

    export interface ComicsStats {
        "total_comics": number
        "published_comics": number
        "pending_comics": number
        "total_views": number
        "storage_bytes": number
        "top_liked": TopLikedComic[]
    }

    export interface CommentData {
        id: string
        "comic_id": string
        "user_id": string
        "parent_id": string
        "body_text": string
        "created_at": string
        replies: CommentData[]
    }

    export interface CreateComicParams {
        title: string
        author: string
        description: string
        "content_language": string
        "cover_key": string
        "file_key": string
        "page_keys": string[]
        "file_size_bytes": number
        "min_tier_id": string
        "age_rating": string
        "is_premium": boolean
        tags: string[]
        "upload_session_id": string
    }

    export interface CreateCommentParams {
        "body_text": string
        "parent_id": string
    }

    export interface CreateSeriesParams {
        title: string
        description: string
    }

    export interface LikeStatus {
        liked: boolean
        favorited: boolean
        disliked: boolean
    }

    export interface ListComicsParams {
        Page: number
        Limit: number
        Language: string
        Search: string
        Tag: string
        Sort: string
        ExcludeMature: string
    }

    export interface ListComicsResponse {
        comics: Comic[]
        total: number
    }

    export interface ListCommentsResponse {
        comments: CommentData[]
    }

    export interface ListPendingResponse {
        comics: PendingComic[]
        total: number
    }

    export interface ListSeriesResponse {
        series: Series[]
    }

    export interface PendingComic {
        id: string
        title: string
        "uploader_id": string
        status: string
        "created_at": string
    }

    export interface PendingComicsParams {
        Page: number
        Limit: number
        Search: string
        Sort: string
        SortDir: string
    }

    export interface RecycleBinParams {
        Page: number
        Limit: number
        Search: string
        Sort: string
        SortDir: string
        FilterStatus: string
        FilterAuthor: string
        FilterTitle: string
    }

    export interface RejectParams {
        reason: string
    }

    export interface SeedComicsResponse {
        created: number
        skipped: number
        message: string
    }

    export interface SeedEngagementResponse {
        comments: number
        reactions: number
        skipped: number
    }

    export interface SeedParams {
        token: string
    }

    export interface Series {
        id: string
        title: string
        slug: string
        description: string
        "uploader_id": string
        "created_at": string
    }

    export interface ToggleDislikeResponse {
        disliked: boolean
        "dislike_count": number
    }

    export interface ToggleFavResponse {
        favorited: boolean
        "fav_count": number
    }

    export interface ToggleLikeResponse {
        liked: boolean
        "like_count": number
    }

    export interface TopLikedComic {
        id: string
        title: string
        slug: string
        "cover_key": string
        "like_count": number
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.AdminAuditLogs = this.AdminAuditLogs.bind(this)
            this.AdminListComics = this.AdminListComics.bind(this)
            this.ApproveComic = this.ApproveComic.bind(this)
            this.ArchiveComic = this.ArchiveComic.bind(this)
            this.BatchGetComics = this.BatchGetComics.bind(this)
            this.BulkModerate = this.BulkModerate.bind(this)
            this.CommentStream = this.CommentStream.bind(this)
            this.CreateComic = this.CreateComic.bind(this)
            this.CreateComment = this.CreateComment.bind(this)
            this.CreateSeries = this.CreateSeries.bind(this)
            this.DeleteComic = this.DeleteComic.bind(this)
            this.DeleteComment = this.DeleteComment.bind(this)
            this.DevSeedComics = this.DevSeedComics.bind(this)
            this.DevSeedEngagement = this.DevSeedEngagement.bind(this)
            this.FollowSeries = this.FollowSeries.bind(this)
            this.GetComic = this.GetComic.bind(this)
            this.GetComicsStats = this.GetComicsStats.bind(this)
            this.GetLikeStatus = this.GetLikeStatus.bind(this)
            this.GetSeries = this.GetSeries.bind(this)
            this.ListComics = this.ListComics.bind(this)
            this.ListComments = this.ListComments.bind(this)
            this.ListSeries = this.ListSeries.bind(this)
            this.MyComics = this.MyComics.bind(this)
            this.PendingComics = this.PendingComics.bind(this)
            this.RSSFeed = this.RSSFeed.bind(this)
            this.RecycleBin = this.RecycleBin.bind(this)
            this.RejectComic = this.RejectComic.bind(this)
            this.RestoreComic = this.RestoreComic.bind(this)
            this.SeriesComics = this.SeriesComics.bind(this)
            this.ToggleDislike = this.ToggleDislike.bind(this)
            this.ToggleFavorite = this.ToggleFavorite.bind(this)
            this.ToggleLike = this.ToggleLike.bind(this)
            this.UnfollowSeries = this.UnfollowSeries.bind(this)
        }

        public async AdminAuditLogs(): Promise<AuditLogsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/audit-logs`)
            return await resp.json() as AuditLogsResponse
        }

        public async AdminListComics(params: AdminListComicsParams): Promise<ListComicsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "filter_author": params.FilterAuthor,
                "filter_status": params.FilterStatus,
                "filter_title":  params.FilterTitle,
                limit:           String(params.Limit),
                page:            String(params.Page),
                search:          params.Search,
                sort:            params.Sort,
                "sort_dir":      params.SortDir,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/comics`, undefined, {query})
            return await resp.json() as ListComicsResponse
        }

        public async ApproveComic(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/moderation/comics/${encodeURIComponent(id)}/approve`)
        }

        public async ArchiveComic(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/admin/comics/${encodeURIComponent(id)}/archive`)
        }

        public async BatchGetComics(params: BatchComicsParams): Promise<ListComicsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/comics-batch`, JSON.stringify(params))
            return await resp.json() as ListComicsResponse
        }

        public async BulkModerate(params: BulkActionParams): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/moderation/bulk`, JSON.stringify(params))
        }

        public async CommentStream(method: "GET", id: string, body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/comments-stream/${encodeURIComponent(id)}`, body, options)
        }

        public async CreateComic(params: CreateComicParams): Promise<Comic> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/comics`, JSON.stringify(params))
            return await resp.json() as Comic
        }

        public async CreateComment(id: string, params: CreateCommentParams): Promise<CommentData> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/comics/${encodeURIComponent(id)}/comments`, JSON.stringify(params))
            return await resp.json() as CommentData
        }

        public async CreateSeries(params: CreateSeriesParams): Promise<Series> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/series`, JSON.stringify(params))
            return await resp.json() as Series
        }

        public async DeleteComic(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/comics/${encodeURIComponent(id)}`)
        }

        public async DeleteComment(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/comments/${encodeURIComponent(id)}`)
        }

        public async DevSeedComics(params: SeedParams): Promise<SeedComicsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/dev/seed-comics`, JSON.stringify(params))
            return await resp.json() as SeedComicsResponse
        }

        public async DevSeedEngagement(params: SeedParams): Promise<SeedEngagementResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/dev/seed-engagement`, JSON.stringify(params))
            return await resp.json() as SeedEngagementResponse
        }

        public async FollowSeries(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/series/${encodeURIComponent(id)}/follow`)
        }

        public async GetComic(slug: string): Promise<Comic> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/comics/${encodeURIComponent(slug)}`)
            return await resp.json() as Comic
        }

        public async GetComicsStats(): Promise<ComicsStats> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/comics-stats`)
            return await resp.json() as ComicsStats
        }

        public async GetLikeStatus(id: string): Promise<LikeStatus> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/comics/${encodeURIComponent(id)}/like-status`)
            return await resp.json() as LikeStatus
        }

        public async GetSeries(id: string): Promise<Series> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/series/${encodeURIComponent(id)}`)
            return await resp.json() as Series
        }

        public async ListComics(params: ListComicsParams): Promise<ListComicsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "exclude_mature": params.ExcludeMature,
                language:         params.Language,
                limit:            String(params.Limit),
                page:             String(params.Page),
                search:           params.Search,
                sort:             params.Sort,
                tag:              params.Tag,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/comics`, undefined, {query})
            return await resp.json() as ListComicsResponse
        }

        public async ListComments(id: string): Promise<ListCommentsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/comics/${encodeURIComponent(id)}/comments`)
            return await resp.json() as ListCommentsResponse
        }

        public async ListSeries(): Promise<ListSeriesResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/series`)
            return await resp.json() as ListSeriesResponse
        }

        public async MyComics(): Promise<ListComicsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/uploader/comics`)
            return await resp.json() as ListComicsResponse
        }

        public async PendingComics(params: PendingComicsParams): Promise<ListPendingResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:      String(params.Limit),
                page:       String(params.Page),
                search:     params.Search,
                sort:       params.Sort,
                "sort_dir": params.SortDir,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/moderation/comics`, undefined, {query})
            return await resp.json() as ListPendingResponse
        }

        public async RSSFeed(method: "GET", body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/rss`, body, options)
        }

        public async RecycleBin(params: RecycleBinParams): Promise<ListComicsResponse> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "filter_author": params.FilterAuthor,
                "filter_status": params.FilterStatus,
                "filter_title":  params.FilterTitle,
                limit:           String(params.Limit),
                page:            String(params.Page),
                search:          params.Search,
                sort:            params.Sort,
                "sort_dir":      params.SortDir,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/recycle-bin`, undefined, {query})
            return await resp.json() as ListComicsResponse
        }

        public async RejectComic(id: string, params: RejectParams): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/moderation/comics/${encodeURIComponent(id)}/reject`, JSON.stringify(params))
        }

        public async RestoreComic(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("POST", `/admin/comics/${encodeURIComponent(id)}/restore`)
        }

        public async SeriesComics(id: string): Promise<ListComicsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/series/${encodeURIComponent(id)}/comics`)
            return await resp.json() as ListComicsResponse
        }

        public async ToggleDislike(id: string): Promise<ToggleDislikeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/comics/${encodeURIComponent(id)}/dislike`)
            return await resp.json() as ToggleDislikeResponse
        }

        public async ToggleFavorite(id: string): Promise<ToggleFavResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/comics/${encodeURIComponent(id)}/favorite`)
            return await resp.json() as ToggleFavResponse
        }

        public async ToggleLike(id: string): Promise<ToggleLikeResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/comics/${encodeURIComponent(id)}/like`)
            return await resp.json() as ToggleLikeResponse
        }

        public async UnfollowSeries(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/series/${encodeURIComponent(id)}/follow`)
        }
    }
}

export namespace reading {
    export interface ContinueReadingItem {
        "comic_id": string
        "current_page": number
        "total_pages": number
        "updated_at": string
    }

    export interface ContinueReadingResponse {
        items: ContinueReadingItem[]
    }

    export interface DownloadResponse {
        allowed: boolean
        used: number
        limit: number
        message: string
    }

    export interface Progress {
        id: string
        "user_id": string
        "comic_id": string
        "current_page": number
        "total_pages": number
        completed: boolean
        "updated_at": string
    }

    export interface ReadingStats {
        "total_downloads": number
    }

    export interface SaveProgressParams {
        "current_page": number
        "total_pages": number
        completed: boolean
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.ContinueReading = this.ContinueReading.bind(this)
            this.GetProgress = this.GetProgress.bind(this)
            this.GetReadingStats = this.GetReadingStats.bind(this)
            this.RecordDownload = this.RecordDownload.bind(this)
            this.SaveProgress = this.SaveProgress.bind(this)
        }

        public async ContinueReading(): Promise<ContinueReadingResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading-continue`)
            return await resp.json() as ContinueReadingResponse
        }

        public async GetProgress(comicId: string): Promise<Progress> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/reading/${encodeURIComponent(comicId)}`)
            return await resp.json() as Progress
        }

        public async GetReadingStats(): Promise<ReadingStats> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/reading-stats`)
            return await resp.json() as ReadingStats
        }

        public async RecordDownload(comicId: string): Promise<DownloadResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/comics/${encodeURIComponent(comicId)}/download`)
            return await resp.json() as DownloadResponse
        }

        public async SaveProgress(comicId: string, params: SaveProgressParams): Promise<Progress> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/reading/${encodeURIComponent(comicId)}`, JSON.stringify(params))
            return await resp.json() as Progress
        }
    }
}

export namespace tiers {
    export interface AutoLinkPlanParams {
        Host: string
    }

    export interface AutoLinkPlanResponse {
        "provider_plan_id": string
        "plan_name": string
    }

    export interface ListPlansResponse {
        plans: Plan[]
    }

    export interface ListTiersResponse {
        tiers: Tier[]
    }

    export interface MatrixStatus {
        complete: boolean
    }

    export interface Plan {
        id: string
        "tier_id": string
        name: string
        interval: string
        "price_usd_cents": number
        "quota_downloads": number
        features: string[]
        "is_active": boolean
        "provider_plan_id": string
        "provider_interval_days": number
        "created_at": string
    }

    export interface Tier {
        id: string
        name: string
        description: string
        "sort_order": number
        "created_at": string
    }

    export interface UnlinkAllPlansResponse {
        count: number
    }

    export interface UpdatePlanProviderParams {
        "provider_plan_id": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.AutoLinkPlan = this.AutoLinkPlan.bind(this)
            this.GetTier = this.GetTier.bind(this)
            this.ListPlans = this.ListPlans.bind(this)
            this.ListTiers = this.ListTiers.bind(this)
            this.PlanMatrixStatus = this.PlanMatrixStatus.bind(this)
            this.PlansReady = this.PlansReady.bind(this)
            this.UnlinkAllPlans = this.UnlinkAllPlans.bind(this)
            this.UpdatePlanProviderID = this.UpdatePlanProviderID.bind(this)
        }

        public async AutoLinkPlan(id: string, params: AutoLinkPlanParams): Promise<AutoLinkPlanResponse> {
            // Convert our params into the objects we need for the request
            const headers = makeRecord<string, string>({
                host: params.Host,
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/plans/link/${encodeURIComponent(id)}`, undefined, {headers})
            return await resp.json() as AutoLinkPlanResponse
        }

        public async GetTier(id: string): Promise<Tier> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/tiers/${encodeURIComponent(id)}`)
            return await resp.json() as Tier
        }

        public async ListPlans(): Promise<ListPlansResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/plans`)
            return await resp.json() as ListPlansResponse
        }

        public async ListTiers(): Promise<ListTiersResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/tiers`)
            return await resp.json() as ListTiersResponse
        }

        public async PlanMatrixStatus(): Promise<MatrixStatus> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/plans/matrix-status`)
            return await resp.json() as MatrixStatus
        }

        public async PlansReady(): Promise<MatrixStatus> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/plans/ready`)
            return await resp.json() as MatrixStatus
        }

        public async UnlinkAllPlans(): Promise<UnlinkAllPlansResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/admin/plans/unlink`)
            return await resp.json() as UnlinkAllPlansResponse
        }

        public async UpdatePlanProviderID(id: string, params: UpdatePlanProviderParams): Promise<void> {
            await this.baseClient.callTypedAPI("PATCH", `/admin/plans/${encodeURIComponent(id)}`, JSON.stringify(params))
        }
    }
}

export namespace upload {
    export interface CloudflareUploadResponse {
        uploadURL: string
        imageID: string
    }

    export interface ConfirmPartParams {
        number: number
        key: string
        size: number
        etag: string
    }

    export interface CreateSessionParams {
        mode: string
    }

    export interface ListSessionsResponse {
        sessions: UploadSession[]
    }

    export interface Part {
        number: number
        key: string
        etag: string
        size: number
    }

    export interface PresignParams {
        number: number
        key: string
    }

    export interface PresignResponse {
        number: number
        key: string
        url: string
    }

    export interface StorageStats {
        "cf_configured": boolean
        "cf_images_count": number
    }

    export interface UploadSession {
        id: string
        "user_id": string
        mode: string
        status: string
        "s3_prefix": string
        parts: Part[]
        "expires_at": string
        "created_at": string
    }

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.AbortSession = this.AbortSession.bind(this)
            this.CloudflarePresignedUpload = this.CloudflarePresignedUpload.bind(this)
            this.ConfirmPart = this.ConfirmPart.bind(this)
            this.CreateSession = this.CreateSession.bind(this)
            this.GetSession = this.GetSession.bind(this)
            this.GetStorageStats = this.GetStorageStats.bind(this)
            this.ListActiveSessions = this.ListActiveSessions.bind(this)
            this.PresignUpload = this.PresignUpload.bind(this)
            this.ServeMedia = this.ServeMedia.bind(this)
        }

        public async AbortSession(id: string): Promise<void> {
            await this.baseClient.callTypedAPI("DELETE", `/upload-sessions/${encodeURIComponent(id)}`)
        }

        public async CloudflarePresignedUpload(): Promise<CloudflareUploadResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/media/cloudflare/upload-url`)
            return await resp.json() as CloudflareUploadResponse
        }

        public async ConfirmPart(id: string, params: ConfirmPartParams): Promise<UploadSession> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/upload-sessions/${encodeURIComponent(id)}/parts`, JSON.stringify(params))
            return await resp.json() as UploadSession
        }

        public async CreateSession(params: CreateSessionParams): Promise<UploadSession> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/upload-sessions`, JSON.stringify(params))
            return await resp.json() as UploadSession
        }

        public async GetSession(id: string): Promise<UploadSession> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/upload-sessions/${encodeURIComponent(id)}`)
            return await resp.json() as UploadSession
        }

        public async GetStorageStats(): Promise<StorageStats> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/admin/storage-stats`)
            return await resp.json() as StorageStats
        }

        public async ListActiveSessions(): Promise<ListSessionsResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("GET", `/upload-sessions`)
            return await resp.json() as ListSessionsResponse
        }

        public async PresignUpload(id: string, params: PresignParams): Promise<PresignResponse> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI("POST", `/upload-sessions/${encodeURIComponent(id)}/presign`, JSON.stringify(params))
            return await resp.json() as PresignResponse
        }

        public async ServeMedia(method: "GET", key: string, body?: RequestInit["body"], options?: CallParameters): Promise<globalThis.Response> {
            return this.baseClient.callAPI(method, `/media/${encodeURIComponent(key)}`, body, options)
        }
    }
}



function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "method" | "body" | "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}

// AuthDataGenerator is a function that returns a new instance of the authentication data required by this API
export type AuthDataGenerator = () =>
  | auth.AuthParams
  | Promise<auth.AuthParams | undefined>
  | undefined;

// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
    readonly authGenerator?: AuthDataGenerator

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "comics-galore-backend-v5k2-Generated-TS-Client (Encore/v1.57.13)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }

        // Setup an authentication data generator using the auth data token option
        if (options.auth !== undefined) {
            const auth = options.auth
            if (typeof auth === "function") {
                this.authGenerator = auth
            } else {
                this.authGenerator = () => auth
            }
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        let authData: auth.AuthParams | undefined;

        // If authorization data generator is present, call it and add the returned data to the request
        if (this.authGenerator) {
            const mayBePromise = this.authGenerator();
            if (mayBePromise instanceof Promise) {
                authData = await mayBePromise;
            } else {
                authData = mayBePromise;
            }
        }

        if (authData) {
            const data: CallParameters = {};

            data.headers = makeRecord<string, string>({
                authorization: authData.Authorization,
            });

            return data;
        }

        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        return this.callAPI(method, path, body, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(method: string, path: string, body?: RequestInit["body"], params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
            method,
            body: body ?? null,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}
