name: Deploy Dev

on:
  push:
    branches: [dev]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: dev
      backend_url: https://dev-3cxq6.encr.app
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      TURNSTILE_SITEKEY: ${{ secrets.TURNSTILE_SITEKEY }}
