name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: ./.github/workflows/deploy-app.yml
    with:
      environment: prod
      backend_url: https://production-3cxq6.encr.app
    secrets:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      TURNSTILE_SITEKEY: ${{ secrets.TURNSTILE_SITEKEY }}
